name: track_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  scroll_date_picker: ^3.6.0
  google_fonts: ^3.0.1
  flutter_svg_provider: ^1.0.3
  flutter_screenutil: ^5.5.4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/bg.png
     - assets/images/bg_button.svg
     - assets/images/top.svg
     - assets/images/bottom.svg
     - assets/images/midIn.svg
     - assets/images/midOut.svg
